-- AlterTable
ALTER TABLE "Comment" ALTER COLUMN "lastUpdate" SET DEFAULT CURRENT_TIMESTAMP;

-- AlterTable
ALTER TABLE "Post" ALTER COLUMN "lastUpdate" SET DEFAULT CURRENT_TIMESTAMP;

-- AlterTable
ALTER TABLE "SuggestedTopics" ADD COLUMN     "downvote" TEXT[] DEFAULT ARRAY[]::TEXT[],
ADD COLUMN     "upvote" TEXT[] DEFAULT ARRAY[]::TEXT[];

-- AlterTable
ALTER TABLE "Users" ADD COLUMN     "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP;
